[package]
name = "scoped-sink"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["Dheatly23 <71598333+Dheatly23@users.noreply.github.com>"]
license = "Apache-2.0"

[dependencies]
futures-core = "0.3"
futures-sink = "0.3"
parking_lot = "0.12"
pin-project-lite = "0.2"

[dev-dependencies]
anyhow = "1"

[dev-dependencies.futures-util]
version = "0.3"
features = [
  "sink",
]

[dev-dependencies.tokio]
version = "1"
features = [
  "test-util",
  "macros",
]
